services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    restart: always

  whoami:
    image: traefik/whoami
    container_name: whoami
    ports:
      - "8081:80"
    restart: always

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma-data:/app/data
    restart: always

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - npm-data:/data
      - npm-letsencrypt:/etc/letsencrypt
    restart: always

volumes:
  uptime-kuma-data:
  npm-data:
  npm-letsencrypt:
